### ISSUE TITLE
0.10.3 happens.

### ISSUE THREAD

**Issue by Christophe31** [geekq/impressive#1]
A new release of impressive came in 2010.

You may want to update your fork or contact the main developer to merge your work.

http://impressive.sourceforge.net/news.php

**Comment by geekq** [comment]
The implementation of the original impressive is unfortunately extremely repetitive making any change expensive. This is why the development of the original project slowed down. There is also no chance for continuously merging my changes into the original implementation.

Unfortunately, I do not have time to completely refactor the original implementation and so I have limited myself to just implementing the dual head support and some sort of presenter screen, where I can also see the next slide.
